language: node_js
node_js:
  - 12
script:
  - yarn run test
  - if [[ $TRAVIS_EVENT_TYPE != 'pull_request' ||  $TRAVIS_PULL_REQUEST_SLUG != $TRAVIS_REPO_SLUG ]]; then npx chromatic --project-token $CHROMATIC_TOKEN; fi
