# This is a basic workflow to help you get started with Actions

name: chromatic-pr

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [dev]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Установка yarn
        id: yarn-setup
        run: |
          yarn policies set-version 1.19.1
          echo "::set-output name=cache_dir::$(yarn cache dir)"

      - name: Установка зависимостей
        run: yarn --frozen-lockfile

      - name: chromatic pull request publish
        run: |
          git status
          npx chromatic --project-token=${{ secrets.CHROMATIC_TOKEN }} --patch-build=${{ github.head_ref }}...${{ github.base_ref }}
