name: chromatic-pr

on:
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Установка yarn
        id: yarn-setup
        run: |
          yarn policies set-version 1.19.1
          echo "::set-output name=cache_dir::$(yarn cache dir)"

      - name: Настройка кэширования зависимостей
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-setup.outputs.cache_dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Установка зависимостей
        run: yarn --frozen-lockfile

      - name: chromatic pull request publish
        run: |
          git fetch origin
          git checkout -b ${{ github.base_ref }} origin/${{ github.base_ref }}
          git checkout -b ${{ github.head_ref }} origin/${{ github.head_ref }}
          git checkout ${{ github.head_ref }}
          npx chromatic --project-token=${{ secrets.CHROMATIC_TOKEN }} --patch-build=${{ github.head_ref }}...${{ github.base_ref }}
